server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-java
  #配置rabbitMq 服务器
  rabbitmq:
    host: 82.157.123.123
    port: 5672
    username: test
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: test
